#!/usr/bin/env bash
#
# Usage: ./deploy [STAGE]
#
# Possible stage values: test, prod
#
# Usage example: ./deploy prod
#

deploy_stage=$1

thisDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$thisDir/deployer" || exit 1

"${thisDir}/vendor/bin/dep" deploy -vvv stage="$deploy_stage"
exitcode=$?

cd "$thisDir"

exit ${exitcode}
