hosts:
  testing:
    hostname: sysops.webonary.work
    deploy_path: /var/www/sites/webonary-test
    # NB: set the "branch" you want to deploy to webonary.work
    branch: feature/Issue-813
    labels:
      stage: test

  staging:
    hostname: sysops.webonary.work
    deploy_path: /var/www/sites/webonary
    branch: develop
    labels:
      stage: staging

  production:
    hostname: sysops.webonary.org
    deploy_path: /var/www/sites/webonary
    branch: master
    labels:
      stage: production
