hosts:
  testing:
    hostname: sysops.webonary.work
    deploy_path: /var/www/sites/webonary
    # NB: set the "branch" you want to deploy to webonary.work.
    # For feature branches, use "feature/name".
    branch: feature/dev-deploy
    labels:
      stage: test

  staging:
    hostname: sysops.webonary.work
    deploy_path: /var/www/sites/webonary
    branch: develop
    labels:
      stage: staging

  production:
    hostname: sysops.webonary.org
    deploy_path: /var/www/sites/webonary
    branch: master
    labels:
      stage: production
